version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      test-dependencies:
        patterns:
          - xunit*
          - Microsoft.NET.Test.Sdk
          - coverlet.*
          - NJsonSchema
    ignore:
      - dependency-name: Netezos
        update-types:
          - version-update:semver-major
