name: Publish on GitHub Pages

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  publish:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: github-pages
      url: https://github.com
    steps:
      - uses: actions/checkout@v7

      - name: Build documentation
        uses: nikeee/docfx-action@b9c2cf92e3b4aa06878a1410833a8828b4bdcd26 # v1.0.0
        with:
          args: docs/docfx.json

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          publish_branch: gh-pages
          force_orphan: true
