name: Publish on GitHub Pages

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  publish:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://github.com
    steps:
      - uses: actions/checkout@v2

      - name: Build documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json

      - name: Publish documentation
        uses: maxheld83/ghpages@master
        env:
          BUILD_DIR: docs/_site
          GH_PAT: ${{ secrets.PAT }}
