name: Release notifications

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  notify:
    name: Make release and notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Get tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Make release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Netezos ${{ env.RELEASE_VERSION }} has been released 😎
            NuGet Package will be available in a few minutes.
            More info at https://github.com/baking-bad/netezos/releases/tag/${{ env.RELEASE_VERSION }}

      - name: Send Slack notification
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          args: |
            Netezos ${{ env.RELEASE_VERSION }} has been released 😎
            NuGet Package will be available in a few minutes.
            More info at https://github.com/baking-bad/netezos/releases/tag/${{ env.RELEASE_VERSION }}