name: Release notifications

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  notify:
    name: Make release and notify
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Make release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true

      - name: Send Telegram notification
        uses: appleboy/telegram-action@v1.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Netezos ${{ env.RELEASE_VERSION }} has been released 😎
            NuGet Package will be available in a few minutes.
            More info at https://github.com/baking-bad/netezos/releases/tag/${{ env.RELEASE_VERSION }}

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              Netezos ${{ env.RELEASE_VERSION }} has been released 😎
              NuGet Package will be available in a few minutes.
              More info at https://github.com/baking-bad/netezos/releases/tag/${{ env.RELEASE_VERSION }}
