name: Publish on NuGet

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Build and publish package
    runs-on: ubuntu-latest
    environment:
      name: nuget
      url: https://github.com
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.PAT }}

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '9.0.x'

      - name: Build and publish package if version changed
        uses: alirezanet/publish-nuget@e276c40afeb2a154046f0997820f2a9ea74832d9 # v3.1.0
        with:
          PROJECT_FILE_PATH: Netezos/Netezos.csproj
          PACKAGE_NAME: Netezos
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
